color: cyan
fieldLayouts:
  8f8961ce-b8f9-44b2-8ade-61b7a791585f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-23T00:52:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7e4b4add-061e-4eab-92df-597242f18a90 # Primary Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6dcac474-fd3a-484b-a836-176a941596ba
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T01:21:20+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4d1d0ace-6df5-4e05-91b0-1d1ce27d4f3b # Social Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a41ffe4-3cf0-476b-bfe2-c04a0f5db66c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cbdd056d-244a-4dc8-821c-06f875fcca10
        userCondition: null
handle: footer
hasTitleField: false
icon: compass
name: Footer
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Footer
titleTranslationKeyFormat: null
titleTranslationMethod: site
