color: blue
fieldLayouts:
  7b9c1555-c58e-40a8-9db5-27785ba1e2c4:
    cardView:
      - 'layoutElement:e66a1ce8-b8b9-4995-b7cf-456a8e43eff9'
      - 'layoutElement:40fdf764-e36c-467b-a7a9-4dc2ffd5a4df'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-05T03:41:07+00:00'
            elementCondition: null
            fieldUid: 21db7ac8-7f8f-4c6d-a93b-52418c34492c # Year
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 582d1ba6-ac48-4124-8202-3eb246013891
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-04T01:59:43+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 01cf6d66-ef19-449a-b210-3ee151767ae3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T02:01:34+00:00'
            elementCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: subHead
            includeInCards: true
            instructions: null
            label: 'Sub Head'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e66a1ce8-b8b9-4995-b7cf-456a8e43eff9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T02:01:34+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40fdf764-e36c-467b-a7a9-4dc2ffd5a4df
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 936adc8a-d141-4f0a-817f-ce2756d4ba65
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T04:42:14+00:00'
            elementCondition: null
            fieldUid: 451ebed9-368d-4404-a7f4-1c565c0dfc4a # Color
            handle: null
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f47025ea-51f8-4636-9d11-c7095203cb70
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 22ae623b-97b7-4e30-833e-956160a84f69
        userCondition: null
handle: headerBlock
hasTitleField: true
icon: heading
name: 'Header Block'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
