color: null
fieldLayouts:
  def09ee6-64e3-4896-8ed8-3ca55ffaaa7f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-04T01:52:24+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2bdfab6a-af0f-4bd0-bdfb-406df66da8a5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-04T02:15:46+00:00'
            elementCondition: null
            fieldUid: 48f6a218-2886-43f7-80cc-13633d3687a6 # History Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddefa8fc-fe30-4fb9-b9ce-aad738ae38a0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 417be245-cdf9-48c0-ab47-573c08df0b2f
        userCondition: null
handle: history
hasTitleField: true
icon: ''
name: History
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
