color: sky
fieldLayouts:
  58eb27ed-c9fa-458b-972b-59bb97f1299e:
    cardView:
      - 'layoutElement:1090b3af-4104-44b4-856d-6ae7a4414142'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-18T18:36:16+00:00'
            elementCondition: null
            heading: 'Top Banner'
            type: craft\fieldlayoutelements\Heading
            uid: c465d0b0-dff1-461e-8595-aabd66b99140
            userCondition: null
          -
            dateAdded: '2024-08-21T23:09:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1090b3af-4104-44b4-856d-6ae7a4414142
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T23:09:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ae97b4e4-7938-4735-b734-84f98ec34af2 # Banner Buttons
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a882504e-b46a-4099-a490-7b739df7545e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T04:41:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdf09a59-9eed-425d-9fbf-179f8006b17e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T20:03:45+00:00'
            elementCondition: null
            heading: 'First Slider'
            type: craft\fieldlayoutelements\Heading
            uid: 2c7a48e1-34f9-49cb-8204-5feff4771579
            userCondition: null
          -
            dateAdded: '2024-11-26T04:53:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: sliderHeader
            includeInCards: false
            instructions: null
            label: 'Slider Header'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4a16dfe-0e7c-415b-897d-54ec75de7a03
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-14T02:16:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: fixedSlideAsset
            includeInCards: false
            instructions: null
            label: __blank__
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7a23981-db13-4a4a-83c6-7630fda02f58
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T04:53:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2bb0df43-098d-4091-a1e0-967b00fdcb6c # Slides
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f2e4312-2214-41cb-bd13-35a36a45b12e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T21:17:18+00:00'
            elementCondition: null
            heading: 'Video Between Sliders'
            type: craft\fieldlayoutelements\Heading
            uid: bc9d0095-a86d-46b5-9a9a-037511ad8f7b
            userCondition: null
          -
            dateAdded: '2024-12-16T21:17:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: middleAsset
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67e763d2-1b4c-4e07-a34c-010561d25d4d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T20:03:45+00:00'
            elementCondition: null
            heading: 'Second Slider'
            type: craft\fieldlayoutelements\Heading
            uid: 97d17538-1d68-43c5-b50f-e9064dcac50c
            userCondition: null
          -
            dateAdded: '2024-12-16T19:35:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: sliderHeader2
            includeInCards: false
            instructions: null
            label: 'Slider Header'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 819137dc-1bae-4d14-881f-4950a716063f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-18T18:36:16+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'Add a double slide to have two blocks stack on top of one another. Add a single slide for full height.'
            type: craft\fieldlayoutelements\Tip
            uid: 924adf0f-12f8-4934-919f-8bc23f11b0d6
            userCondition: null
          -
            dateAdded: '2024-12-16T20:03:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 62c3a695-96b4-43f5-ac43-eb27a6cfc3f9 # Slides
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae713bfb-59e1-4b17-a42b-9cdd8214e74f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T22:04:31+00:00'
            elementCondition: null
            heading: 'Bottom Banner'
            type: craft\fieldlayoutelements\Heading
            uid: 3594c168-2ee1-4b24-9d2a-91b733158ab5
            userCondition: null
          -
            dateAdded: '2024-12-16T22:12:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: textBottom
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b3aa162f-ab06-4ad3-8572-04cdf29668c7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-09T23:03:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8c107cc9-2cb0-47b2-aa42-a82e26aadd14 # CTA Buttons
            handle: buttonsBottom
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ade35be7-755a-417b-a0ac-d0fb5994f300
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-16T22:12:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: assetBottom
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da55ec2b-bffe-43ff-88e0-462e5731924f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e51f8a6c-382c-49e4-a57e-54937ff4e853
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-09-24T20:36:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4561fe05-31a8-4fcd-86a8-cb4e675e6bb8 # Slide Time
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17a82337-e15a-4935-91da-9f1a6ab334a0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T23:18:05+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bda53640-24b3-44f4-8c8b-ee991f1addba # Text Alignment
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b7a89ee-57f2-4ada-b429-15b69621d8e0
            userCondition: null
            warning: null
            width: 25
        name: Settings
        uid: 03e64733-4cff-4c46-9eb7-56a8e2f03640
        userCondition: null
handle: home
hasTitleField: false
icon: house
name: Home
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: Home
titleTranslationKeyFormat: null
titleTranslationMethod: site
