color: null
fieldLayouts:
  ffce58c9-8a92-43fa-9c2b-9dd2b6c83d06:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-07T18:11:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6c3037a-a389-45dc-a0cd-c448e9e6223e # Staff Contact
            handle: null
            includeInCards: false
            instructions: 'Choose a Staff member to be the main point of contact.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2642efc0-92b0-438e-a26d-8e4366240186
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-07T23:03:26+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: fa4cd197-d4e1-4986-8110-3ed568cbfaf4
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-27T00:37:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 92e8b605-fedc-47ac-af4d-a7ef917d730f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-27T00:39:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1146c4d0-8c65-42a7-a57a-07e7f2322c43
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-27T00:39:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: asset
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caa2e4f9-5e75-483e-af00-a215b8e86e32
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T23:22:18+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 598fe136-4186-4427-b46f-dcdcaa9fc13d
            userCondition: null
          -
            dateAdded: '2024-12-03T00:26:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: stickyBlocksHeader
            includeInCards: false
            instructions: null
            label: 'Sticky Blocks Header'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b43447ae-3d31-4a46-a6aa-ff1f680349db
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T23:22:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d2831d4a-7a65-4757-bbf6-66a076fe5e3a # Sticky Blocks
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0e6fd9f4-4549-4504-aee9-68c4a70bade7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bda28db1-2f84-41b9-ad2e-7b38363472ce
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-27T00:46:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 451ebed9-368d-4404-a7f4-1c565c0dfc4a # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a43110f-ec6d-4eb6-b31d-a3105663387c
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 9852d906-1948-48f9-ad84-fafa8f531010
        userCondition: null
handle: landServices
hasTitleField: true
icon: null
name: 'Land & Minerals'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
