color: null
fieldLayouts:
  24fe678f-1c37-402a-ae14-0f83240d9391:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-07T23:03:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f6c3037a-a389-45dc-a0cd-c448e9e6223e # Staff Contact
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff43a0ad-f585-4dd6-a406-42234a267d28
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-07T23:03:13+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: a3e779c0-6993-4f73-b5fa-7503ef5e6b2f
            userCondition: null
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-06T04:25:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 077938c7-c50c-44c8-b69e-e36012a8c332
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T04:27:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a2094f8f-21e4-47cd-878d-603272fea893
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-08T17:26:16+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: null
            includeInCards: false
            instructions: 'Choose an image to associate with this page for social media links and related entries links.'
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 900a2bd8-1b75-46c5-ac98-1904fcedb040
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-08T17:26:16+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 278bc1ee-011e-4e3b-b774-0adcad854724
            userCondition: null
          -
            dateAdded: '2025-05-08T17:01:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4f214814-db96-4951-a3b1-03392ef7ef4d # Entries
            handle: null
            includeInCards: false
            instructions: "Choose other pages on the site that you'd like to display below the listings."
            label: 'Related Entries'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 859c5b60-2099-4d51-90d3-3fc8dbd104c8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-08T17:12:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: entriesText
            includeInCards: false
            instructions: null
            label: 'Related Entries Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd332ddc-a3ae-4245-8b2e-2f431702dc6c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 797ae5a1-b3c7-4230-860b-972e469b7b2d
        userCondition: null
handle: landSales
hasTitleField: true
icon: null
name: 'Land Sales'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
