color: purple
fieldLayouts:
  5d95bd99-c43f-43d8-9318-e6a20adf6ac7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T01:14:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f6c4e4e4-6b58-4da5-9777-ac08feb5c4a8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-08T20:04:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43fbbc16-ba90-4d23-b7fe-419d8631f050
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e453496a-62da-4272-8066-8c64f38d6032
        userCondition: null
handle: page
hasTitleField: true
icon: file
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
