color: red
fieldLayouts:
  25a76be6-e271-4d74-a09b-901516e38a61:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T01:14:44+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 446b6ac8-d66e-4c16-96ac-b8b3d9d8d028
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T01:14:44+00:00'
            elementCondition: null
            fieldUid: 12099acd-6fe1-4370-87e0-eba9eef7a315
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f1cc237-cef8-40fb-9460-9beb675c0499
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b1fa7753-aeec-4bb1-b26f-e1dd50f6b441
        userCondition: null
handle: projectCategory
hasTitleField: true
icon: list
name: 'Project Category'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
