color: null
fieldLayouts:
  c331993d-bae2-4437-b185-62203458504e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-26T05:48:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Service Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0ec78a24-a98c-4daa-ae66-f8c56abc3585
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T05:49:52+00:00'
            elementCondition: null
            fieldUid: 2bb0df43-098d-4091-a1e0-967b00fdcb6c # Slides
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 977c4bae-2b81-4a9f-8046-1da667b2ccf5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 12a2bb17-fd99-47e3-b968-785f926b254d
        userCondition: null
handle: service
hasTitleField: true
icon: null
name: Service
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
