color: teal
fieldLayouts:
  abac4ea7-a4ad-49bb-ae10-343d15a4a23b:
    cardView:
      - 'layoutElement:c390edc7-79dd-485b-a3be-17447e1d0c73'
      - 'layoutElement:7f64e276-6f74-4484-a1ac-659d18eb16a0'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-02T23:18:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 787fd3ae-444c-4cf6-8799-cdc329723fe6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T23:21:15+00:00'
            elementCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: subtitle
            includeInCards: true
            instructions: null
            label: Subtitle
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c390edc7-79dd-485b-a3be-17447e1d0c73
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T23:21:15+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0584ff34-18ce-4f0a-aae8-3c694a88cbb6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-02T23:21:15+00:00'
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f64e276-6f74-4484-a1ac-659d18eb16a0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cd9f3a5c-f838-49e4-925b-783d6e1165f7
        userCondition: null
handle: stickyBlock
hasTitleField: true
icon: cube
name: 'Sticky Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
