color: green
fieldLayouts:
  da3ab5e1-cd9c-4c14-b0c3-6b909d9fbb54:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-10-31T22:32:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 44810511-d8b8-489b-8964-5b2a41a40ad3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-31T22:34:20+00:00'
            elementCondition: null
            fieldUid: a8f5f4f5-00ed-4701-a12b-eda576eb0326 # Date
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7333ba4d-6b99-4315-8464-2001f993d713
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-10-31T22:34:20+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 507776a6-06e8-44c2-83a2-668e8c0be7bd
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-05T00:31:48+00:00'
            elementCondition: null
            fieldUid: f76674b5-1d33-43bb-8e5c-a3c9b37bbc77
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5a7398dd-892c-4be5-b8eb-80ae4f608d0d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f563a4b1-46ee-45e0-ac38-6aa3a5ef9df9
        userCondition: null
handle: video
hasTitleField: true
icon: play
name: Video
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
