baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Crosby Resource Management'
primary: true
siteGroup: 922da0f7-e1c5-45c4-8aa7-49850744589b # Crosby
sortOrder: 1
