columnSuffix: null
handle: ctaButtons
instructions: null
name: 'CTA Buttons'
searchable: false
settings:
  createButtonLabel: 'New Button'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 2a474d4a-c4ce-4af9-8df0-20b69b317f1c # Button
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
