columnSuffix: null
handle: excludeFromTeamPage
instructions: 'Enable this field if you do not want this person to appear on the team page.'
name: 'Exclude From Team Page'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
