columnSuffix: null
handle: slidesLand
instructions: null
name: Slides
searchable: true
settings:
  createButtonLabel: 'New Slide'
  defaultIndexViewMode: cards
  entryTypes:
    - 65b7ac17-5b70-46b3-9aea-143443333ef1 # Single Slide
    - 092b44b6-4a5a-4487-af2a-9caa7dbff37d # Double Slide
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
