columnSuffix: null
handle: slides
instructions: null
name: Slides
searchable: true
settings:
  createButtonLabel: 'New Slide'
  defaultIndexViewMode: cards
  entryTypes:
    - 48e5995c-750c-4886-986e-6d886dd4e850 # Slide
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
