columnSuffix: null
handle: socialLinks
instructions: 'Add social links.'
name: 'Social Links'
searchable: false
settings:
  createButtonLabel: 'New Social Link'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 4016b64a-ad4f-4c26-860a-d746e38c1c52 # Social Link
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
