columnSuffix: null
handle: staffCategory
instructions: 'Choose a category that the staff member belongs in.'
name: 'Staff Category'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: false
  source: 'group:bf576820-9e89-40b9-a7c5-82be152e232e' # Staff
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
