columnSuffix: null
handle: staffContact
instructions: 'Choose a Staff member to be the main point of contact for this listing.'
name: 'Staff Contact'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Add a Staff Contact'
  showCardsInGrid: true
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources:
    - 'section:68cbee1c-920f-40db-8ed7-12382fc9e585' # Staff
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
