defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2e6345b3-c242-4919-be0a-11f0e6afc8c6 # Company
handle: company
maxAuthors: 1
name: Company
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # Crosby Resource Management
    enabledByDefault: true
    hasUrls: true
    template: _pages/company
    uriFormat: 'company/{slug}'
structure:
  maxLevels: null
  uid: 2f5d1dec-c069-45f7-8a54-e11ab3f67584
type: structure
