defaultPlacement: end
enableVersioning: true
entryTypes:
  - cb81f2a5-9202-4f24-98a8-cd3ae8f8a978 # Hunting Lease Listing
handle: huntingLeases
maxAuthors: 1
name: 'Hunting Leases'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - /recreation/hunting-leases
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # Crosby Resource Management
    enabledByDefault: true
    hasUrls: true
    template: _land/_entry
    uriFormat: 'recreation/{slug}'
structure:
  maxLevels: null
  uid: 31ff6b49-fe63-4f09-b6d7-eaa9c99285e5
type: structure
