defaultPlacement: end
enableVersioning: true
entryTypes:
  - 8b433bb6-cab9-45f3-bac0-0eecc02c1cd0 # Navigation Link
handle: navigation
maxAuthors: 1
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # Crosby Resource Management
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: 43e00023-78e1-4e56-8e27-0e324303e2a7
type: structure
