defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: dce03ff5-5f57-481d-b25d-f0224620eb0d # Page
handle: pages
maxAuthors: 1
name: Pages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # Crosby Resource Management
    enabledByDefault: true
    hasUrls: true
    template: _pages/_entry
    uriFormat: '{slug}'
structure:
  maxLevels: null
  uid: 515ce209-3ed0-4c3a-9ed8-09c49c97034e
type: structure
