defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 729b86ad-8f1d-4a29-ad6b-8ea218f8e048 # Hunting Leases
handle: recreation
maxAuthors: 1
name: Recreation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # Crosby Resource Management
    enabledByDefault: true
    hasUrls: true
    template: _land/_entry
    uriFormat: 'recreation/{slug}'
type: channel
